// Generated by CoffeeScript 1.3.3

module.exports = function() {
  return link({
    href: '//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/css/bootstrap-combined.min.css',
    rel: 'stylesheet'
  });
};
