// Generated by CoffeeScript 1.6.2
module.exports = function() {
  return a('.btn.btn-navbar', {
    'data-toggle': 'collapse',
    'data-target': '.nav-collapse'
  }, function() {
    var times, _i, _results;

    _results = [];
    for (times = _i = 0; _i <= 2; times = ++_i) {
      _results.push(span('.icon-bar', ''));
    }
    return _results;
  });
};
