// Generated by CoffeeScript 1.3.3

module.exports = function() {
  return a('.btn.btn-navbar', {
    'data-toggle': 'collaspe',
    'data-target': '.nav-collaspe'
  }, function() {
    var times, _i, _results;
    _results = [];
    for (times = _i = 0; _i <= 2; times = ++_i) {
      _results.push(span('.icon-bar', ''));
    }
    return _results;
  });
};
